### ISSUE TITLE
"ImportError: cannot import name tf_logging" on launch

### ISSUE THREAD

**Issue by Undo1** [JoshData/parsey-mcparseface-server#1]
Have SyntaxNet installed and the demo script seems to work correctly. When I try to run this server (`python server.py`), I get this:

```
~/McParseface/models/syntaxnet/parsey-mcparseface-server(branch:master*) » python server.py
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 290-365-523
Traceback (most recent call last):
  File "/Users/parkererway/McParseface/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/parser_eval.py", line 26, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name tf_logging
Traceback (most recent call last):
  File "/Users/parkererway/McParseface/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/parser_eval.py", line 26, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name tf_logging
Traceback (most recent call last):
  File "/Users/parkererway/McParseface/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/parser_eval.py", line 26, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name tf_logging
Traceback (most recent call last):
  File "/Users/parkererway/McParseface/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/parser_eval.py", line 26, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name tf_logging
```

Any ideas?

**Comment by JoshData** [comment]
Seems like something may have broken upstream. See:

https://github.com/JoshData/models/commit/777e738067692db16dffb01d6d22c136dbacfcd7

Also note that this repo must be used with my fork ^.

**Comment by Undo1** [comment]
@JoshData  Using your repo fixed that problem. The server seems to run fine, and appears to be starting the correct processes, but it hangs when sending it a request. (like `http://localhost:8000/?q=this%20is%20a%20test%20sentence`)

I tested manually running the generated command:

```
$ bazel-bin/syntaxnet/parser_eval --input=stdin --output=stdout-conll --hidden_layer_sizes=64 --arg_prefix=brain_tagger --graph_builder=structured --task_context=syntaxnet/models/parsey_mcparseface/context.pbtxt --model_path=syntaxnet/models/parsey_mcparseface/tagger-params --slim_model --batch_size=1024 --alsologtostderr
```

I typed in a test sentence when it seemed to have stalled, then hit cntrl-D. The process stopped and the parsing came out, so I'm not sure why it's not working in the server. Thoughts?

**Comment by Undo1** [comment]
Strike that, this was caused by me being an idiot. I was cloning your repo, but not the online-parsing branch. Works perfectly now, many thanks!

**Comment by JoshData** [comment]
Fantastic thanks for letting me know it worked! 

On June 7, 2016 1:57:25 PM EDT, Undo1 notifications@github.com wrote:

> Strike that, this was caused by me being an idiot. I was cloning your
> repo, but not the online-parsing branch. Works perfectly now, many
> thanks!
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/JoshData/parsey-mcparseface-server/issues/1#issuecomment-224362093

## 

Josh Tauberer (@JoshData) 

// Sent from my phone.

**Comment by 0x38** [comment]
@JoshData I follow the instructions and my server.py stops at

`I syntaxnet/term_frequency_map.cc:101] Loaded 64036 terms from syntaxnet/models/parsey_mcparseface/word-map. `

I copy your repo and the two files are changed on the online-parsing repo was updated.

why Stops? can you help me with this, please?
