### ISSUE TITLE
Using Parsey McParseface Server on Mac OSX

### ISSUE THREAD

**Issue by bzemen** [JoshData/parsey-mcparseface-server#4]
Hello Josh,

Thank you for sharing your code. I know in your documentation you stated that the server script will only work with your branch and the Ubuntu version of tensor flow. I am trying to run your code from python using Mac OSX, and I was wondering if you know how feasible it will be to alter it to work on Mac OSX? I am able to generate the SyntaxNet output, but not the TensorFlow output. Do you know what the difference is between the standard Tensorflow package the the version that works with your script? Please let me know at your convenience and thanks again!

-Betsy

**Comment by JoshData** [comment]
Hi Betsy. I don't know the answer to your question, except that [here are the differences between the stock models and my models fork](https://github.com/JoshData/models/commit/777e738067692db16dffb01d6d22c136dbacfcd7).

**Comment by bzemen** [comment]
Thanks Josh!
