### ISSUE TITLE
Starting Freezes

### ISSUE THREAD

**Issue by 0x38** [JoshData/parsey-mcparseface-server#6]
@JoshData I follow the instructions and my server.py stops at

> I syntaxnet/term_frequency_map.cc:101] Loaded 64036 terms from syntaxnet/models/parsey_mcparseface/word-map.

I copy your repo and the two files are changed on the online-parsing repo was updated.

why freezes? can you help me with this, please?

**Comment by JoshData** [comment]
Sorry, I'm not able to help.

**Comment by 0x38** [comment]
ok thanks
